baseURL: "https://anthony.truskinger.name"
languageCode: "en-au"
title: "Unreasonable persistence"


theme: ~


MetaDataFormat: "yaml"
DefaultContentLanguage: "en"

Paginate: 10
googleAnalytics: ''
enableRobotsTXT: true
enableGitInfo: true
enableEmoji: true
pluralizeListTitles: false

sitemap:
  changefreq: "monthly"
  priority: 0.5
  filename: "sitemap.xml"  

params:
  author: "Anthony Truskinger"
  sourceRepo: https://github.com/atruskie/blog
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class: "bg-black"
  highlight_class: "red b avenir tracked"
  
  body_classes: "light-gray bg-red georgia"
  link_classes: "hover-red no-underline white-90"
  content_classes: "atruskie-bg-darker-gray"
  panel_classes: "bg-dark-gray"
  copy_font: "avenir"
  heading_font: "georgia"

  featured_image: "/images/blog-cover.jpg"
  recent_posts_number: 5

  twitter: "https://twitter.com/atruskie"
  github: "https://github.com/atruskie"
  linkedin: "https://linkedin.com/in/AnthonyTruskinger/"

  favicon: ""
  description: "Ramblings about programming, technology, and other such things"
  profile_photo: /images/me.jpg

taxonomies:
  tag: "tags"
  category: "categories"
  series: "series"



  